spring:
  application:
    name: eureka-feign-one
server:
  port: 4001
eureka:
  instance:
    prefer-ip-address: true
  #     lease-expiration-duration-in-seconds: 5
  #  healthcheck:
#    enabled: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
logging:
  level:
    com.test.eurekafeignone.controller.FeignOneClient: DEBUG
#     defaultZone: http://xiaoyi:123456@localhost:8761/eureka/
#command.default.execution.isolation.thread.timeoutInMilliseconds=210000
#@HystrixProperty(name = "hystrix.command.default.execution.timeout.enabled", value = "false")
