spring:
  application:
    name: eureka-feign
server:
  port: 5001
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
logging:
  level:
    com.test.eurekafeign.feign.UserFeignClient: DEBUG

